# Generated by Django 3.2.10 on 2021-12-15 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0002_alter_member_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_mer', models.CharField(max_length=30)),
                ('cost', models.IntegerField()),
                ('kind', models.CharField(max_length=30)),
                ('memberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
            options={
                'db_table': 'MERCH',
            },
        ),
    ]
