# Generated by Django 3.2.10 on 2021-12-15 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0002_alter_member_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('content_q', models.TextField()),
                ('create_dttm', models.DateTimeField()),
                ('memberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
            options={
                'db_table': 'QUESTION',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_a', models.TextField()),
                ('create_dttm', models.DateTimeField()),
                ('writerID', models.CharField(max_length=15)),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qna.question')),
            ],
            options={
                'db_table': 'ANSWER',
            },
        ),
    ]
