# Generated by Django 3.2.10 on 2021-12-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "memberID",
                    models.CharField(
                        max_length=15,
                        primary_key=True,
                        serialize=False,
                        verbose_name="User ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=30, verbose_name="Nickname")),
                ("password", models.CharField(max_length=128, verbose_name="Password")),
                ("name_mem", models.CharField(max_length=30, verbose_name="Name")),
                ("email", models.EmailField(max_length=30, verbose_name="Email")),
                (
                    "register_dttm",
                    models.DateTimeField(auto_now_add=True, verbose_name="Registered at"),
                ),
                ("point", models.IntegerField(verbose_name="Point")),
            ],
            options={
                "db_table": "MEMBER",
            },
        ),
    ]
